FROM node:22-alpine

WORKDIR /app

# Cukup copy semua package.json menggunakan wildcard pattern jika memungkinkan, 
# atau copy root package.json dan foldernya.
COPY package*.json ./
COPY service-dapur/package*.json ./service-dapur/
COPY service-distribusi/package*.json ./service-distribusi/
COPY service-inventory/package*.json ./service-inventory/
COPY service-menu/package*.json ./service-menu/
COPY service-sekolah/package*.json ./service-sekolah/

# npm secara otomatis akan menginstall dependensi root DAN seluruh workspace sekaligus
RUN npm install --include=dev

COPY . .

EXPOSE 8080

CMD ["node", "server.js"]